import { getScorpMetadata } from "./scorp-data";
import { Colors } from "./types";

const metadata = require("./metadata.json");
const ids = Object.keys(metadata.entries);

type ColorDistribution = {
  [color: string]: ScorpCount;
};

type ScorpCount = {
  occurrences: number;
  scorps: {
    body_color: Set<string>;
    bg2_color: Set<string>;
    bg_color: Set<string>;
    secondary_color: Set<string>;
    outline_color: Set<string>;
    eye_color: Set<string>;
  };
};

const SCORP_COLORS: ColorDistribution = {};

// Construct SCORP_COLORS object
ids.forEach((scorpId: string) => {
  const metadata = getScorpMetadata(scorpId);

  const attributes = metadata.attributes;
  const colors = metadata.colors;

  for (const [colorLocation, hexCode] of Object.entries(colors) as [
    keyof Colors,
    string
  ][]) {
    if (!SCORP_COLORS[hexCode]) {
      SCORP_COLORS[hexCode] = {
        occurrences: 0,
        scorps: {
          body_color: new Set(),
          bg2_color: new Set(),
          bg_color: new Set(),
          secondary_color: new Set(),
          outline_color: new Set(),
          eye_color: new Set(),
        },
      };
    }

    SCORP_COLORS[hexCode].occurrences++;

    if (attributes.bg_style === "blank" && colorLocation === "bg_color") {
      continue;
    }

    if (!attributes.multicolored && colorLocation === "secondary_color") {
      continue;
    }

    SCORP_COLORS[hexCode].scorps[colorLocation].add(scorpId);
  }
});

// Sort SCORP_COLORS.

const SORTED_COLOR_DISTRIBUTION: string[] = Object.entries(SCORP_COLORS)
  .sort(function (
    [_, sc1]: [string, ScorpCount],
    [__, sc2]: [string, ScorpCount]
  ): number {
    if (sc1.occurrences < sc2.occurrences) {
      return -1;
    }
    if (sc1.occurrences > sc2.occurrences) {
      return 1;
    }
    return 0;
  })
  .map(([color, _]: [string, ScorpCount]): string => color);

console.log(SORTED_COLOR_DISTRIBUTION);

const NAME_LIST = {
  supraPrefixes: ["Dr. ", "Mr. ", "Ms. ", "Mrs. ", "Miss ", "O'"],
  supraSuffixes: [
    "ton",
    "town",
    "smith",
    "maker",
    "craft",
    "master",
    "monger",
    "keeper",
    "stress",
    "izer",
    " jr.",
    " junior",
    " senior",
    ", sr.",
    " ɪ",
    " ɪɪ",
    " ɪɪɪ",
    " ɪᴠ",
    " ᴠ",
    ", PhD.",
    ", B.A.",
  ],
  top100us: [
    "James",
    "Mary",
    "Robert",
    "Patricia",
    "John",
    "Jennifer",
    "Michael",
    "Linda",
    "William",
    "Elizabeth",
    "David",
    "Barbara",
    "Richard",
    "Susan",
    "Joseph",
    "Jessica",
    "Thomas",
    "Sarah",
    "Charles",
    "Karen",
    "Christopher",
    "Nancy",
    "Daniel",
    "Lisa",
    "Matthew",
    "Betty",
    "Anthony",
    "Margaret",
    "Mark",
    "Sandra",
    "Donald",
    "Ashley",
    "Steven",
    "Kimberly",
    "Paul",
    "Emily",
    "Andrew",
    "Donna",
    "Joshua",
    "Michelle",
    "Kenneth",
    "Dorothy",
    "Kevin",
    "Carol",
    "Brian",
    "Amanda",
    "George",
    "Melissa",
    "Edward",
    "Deborah",
    "Ronald",
    "Stephanie",
    "Timothy",
    "Rebecca",
    "Jason",
    "Sharon",
    "Jeffrey",
    "Laura",
    "Ryan",
    "Cynthia",
    "Jacob",
    "Kathleen",
    "Gary",
    "Amy",
    "Nicholas",
    "Shirley",
    "Eric",
    "Angela",
    "Jonathan",
    "Helen",
    "Stephen",
    "Anna",
    "Larry",
    "Brenda",
    "Justin",
    "Pamela",
    "Scott",
    "Nicole",
    "Brandon",
    "Emma",
    "Benjamin",
    "Samantha",
    "Samuel",
    "Katherine",
    "Gregory",
    "Christine",
    "Frank",
    "Debra",
    "Alexander",
    "Rachel",
    "Raymond",
    "Catherine",
    "Patrick",
    "Carolyn",
    "Jack",
    "Janet",
    "Dennis",
    "Ruth",
    "Jerry",
    "Maria",
    "Tyler",
    "Heather",
    "Aaron",
    "Diane",
    "Jose",
    "Virginia",
    "Adam",
    "Julie",
    "Henry",
    "Joyce",
    "Nathan",
    "Victoria",
    "Douglas",
    "Olivia",
    "Zachary",
    "Kelly",
    "Peter",
    "Christina",
    "Kyle",
    "Lauren",
    "Walter",
    "Joan",
    "Ethan",
    "Evelyn",
    "Jeremy",
    "Judith",
    "Harold",
    "Megan",
    "Keith",
    "Cheryl",
    "Christian",
    "Andrea",
    "Roger",
    "Hannah",
    "Noah",
    "Martha",
    "Gerald",
    "Jacqueline",
    "Carl",
    "Frances",
    "Terry",
    "Gloria",
    "Sean",
    "Ann",
    "Austin",
    "Teresa",
    "Arthur",
    "Kathryn",
    "Lawrence",
    "Sara",
    "Jesse",
    "Janice",
    "Dylan",
    "Jean",
    "Bryan",
    "Alice",
    "Joe",
    "Madison",
    "Jordan",
    "Doris",
    "Billy",
    "Abigail",
    "Bruce",
    "Julia",
    "Albert",
    "Judy",
    "Willie",
    "Grace",
    "Gabriel",
    "Denise",
    "Logan",
    "Amber",
    "Alan",
    "Marilyn",
    "Juan",
    "Beverly",
    "Wayne",
    "Danielle",
    "Roy",
    "Theresa",
    "Ralph",
    "Sophia",
    "Randy",
    "Marie",
    "Eugene",
    "Diana",
    "Vincent",
    "Brittany",
    "Russell",
    "Natalie",
    "Elijah",
    "Isabella",
    "Louis",
    "Charlotte",
    "Bobby",
    "Rose",
    "Philip",
    "Alexis",
    "Johnny",
    "Kayla",
  ],
  germanNames: [
    "Alfred",
    "Albrecht",
    "Boris",
    "Bruno",
    "Uli",
    "Ulf",
    "Olaf",
    "Duli",
    "Fanny",
    "Frieda",
    "Franziska",
    "Hans",
    "Hugo",
    "Karl",
    "Ludwig",
    "Granini",
    "Gude",
    "Gundula",
    "Heidi",
    "Hibbel",
    "Maxi",
    "Mini",
    "Meise",
    "Finniboy",
    "Thomas",
    "Baldwin",
    "Franky",
    "Gunther",
    "Hamlet",
    "Kurt",
    "Leon",
    "Louisa",
    "Oskar",
    "Otis",
    "Paul",
    "Sigmund",
    "Salami",
    "Stein",
    "Bob",
  ],
  globalNames: [
    "Oliver",
    "Charlotte",
    "Noah",
    "Olivia",
    "Jack",
    "Amelia",
    "William",
    "Isla",
    "Leo",
    "Mia",
    "Lucas",
    "Ava",
    "Thomas",
    "Grace",
    "Henry",
    "Willow",
    "Charlie",
    "Harper",
    "James",
    "Chloe",
    "Ali",
    "Zahra",
    "Elchin",
    "Zeynab",
    "Vugar",
    "Maryam",
    "Anar",
    "Malak",
    "Elnur",
    "Aylin",
    "Samir",
    "Fatima",
    "Eishan",
    "Nuray",
    "Rashad",
    "Nilay",
    "Ilgar",
    "Inji",
    "Vusal",
    "Daniz",
    "Miguel",
    "Helena",
    "Arthur",
    "Alice",
    "Heitor",
    "Laura",
    "Theo",
    "Valentina",
    "Davi",
    "Heloisa",
    "Gabriel",
    "Sophia",
    "Gael",
    "Lorena",
    "Bernardo",
    "Manuela",
    "Samuel",
    "Cecilia",
    "Pedro",
    "Julia",
    "Mateo",
    "Agustina",
    "Agustin",
    "Isabella",
    "Tomas",
    "Sofia",
    "Santiago",
    "Emilia",
    "Lucas",
    "Isidora",
    "Benjamin",
    "Emma",
    "Vicente",
    "Maite",
    "Maximiliano",
    "Josefa",
    "Joaquin",
    "Florencia",
    "Matias",
    "Maria",
    "Luka",
    "Mia",
    "David",
    "Lucija",
    "Ivan",
    "Sara",
    "Jakov",
    "Ana",
    "Marko",
    "Ema",
    "Petar",
    "Petra",
    "Filip",
    "Lana",
    "Matej",
    "Nika",
    "Mateo",
    "Marta",
    "Leon",
    "Elena",
    "William",
    "Ida",
    "Noah",
    "Emma",
    "Oscar",
    "Alma",
    "Lukas",
    "Ella",
    "Victor",
    "Sofia",
    "Malthe",
    "Freja",
    "Oliver",
    "Josefine",
    "Alfred",
    "Clara",
    "Carl",
    "Anna",
    "Valdemar",
    "Karla",
    "Alois",
    "Elea",
    "Matheo",
    "Lya",
    "Raphael",
    "Elyna",
    "Elliot",
    "Anna",
    "Liam",
    "Lili",
    "Mylan",
    "Noemie",
    "Gabriel",
    "Sophia",
    "Theo",
    "Julia",
    "Lucas",
    "Louise",
    "Mael",
    "Ella",
    "Georgios",
    "Maria",
    "Ioannis",
    "Eleni",
    "Konstantinos",
    "Aikaterini",
    "Dimitrios",
    "Vasiliki",
    "Nikolaos",
    "Sophia",
    "Panagiotis",
    "Angeliki",
    "Vasileios",
    "Georgia",
    "Christos",
    "Dimitra",
    "Athanasios",
    "Kostantina",
    "Michail",
    "Paraskevi",
    "Muhammad",
    "Maryam",
    "Adhvik",
    "Saanvi",
    "Shivansh",
    "Zara",
    "Aarav",
    "Inaya",
    "Ayaan",
    "Aarya",
    "Atharv",
    "Pari",
    "Sai",
    "Ira",
    "Aryan",
    "Fatima",
    "Ishaan",
    "Armayra",
    "Krishna",
    "Kiara",
    "Ori",
    "Tamar",
    "David",
    "Avigail",
    "Ariel",
    "Adele",
    "Noam",
    "Noa",
    "Eitan",
    "Shira",
    "Yosef",
    "Talia",
    "Itai",
    "Yael",
    "Daniel",
    "Sarah",
    "Yonatan",
    "Lia",
    "Lavi",
    "Esther",
    "Haruto",
    "Honoka",
    "Minato",
    "Akari",
    "Haruki",
    "Himari",
    "Sota",
    "Mei",
    "Yuto",
    "Ema",
    "Riku",
    "Yui",
    "Yuito",
    "Mio",
    "Aoto",
    "Ichika",
    "Aoi",
    "Aoi",
    "Hinata",
    "Tsumugi",
    "Santiago",
    "Ximena",
    "Mateo",
    "Valentina",
    "Matias",
    "Maria Fernanda",
    "Diego",
    "Sofia",
    "Sebastian",
    "Maria Jose",
    "Nicolas",
    "Martina",
    "Miguel Angel",
    "Zoe",
    "Alejandro",
    "Mia",
    "Samuel",
    "Dulce Maria",
    "Daniel",
    "Maria Guadalupe",
    "Oliver",
    "Isla",
    "Noah",
    "Amelia",
    "Leo",
    "Olivia",
    "Lucas",
    "Willow",
    "George",
    "Harper",
    "Charlie",
    "Ava",
    "William",
    "Lily",
    "Thomas",
    "Sophie",
    "Hunter",
    "Ella",
    "Nathaniel",
    "Angel",
    "Gabriel",
    "Althea",
    "James",
    "Princess",
    "Francis",
    "Ashley",
    "Joshua",
    "Samantha",
    "Jacon",
    "Sophia",
    "Angelo",
    "Andrea",
    "Daniel",
    "Angela",
    "Alexander",
    "Janine",
    "John Mark",
    "Sofia",
    "Joao",
    "Maria",
    "Martim",
    "Leonor",
    "Rodrigo",
    "Matilde",
    "Santiago",
    "Beatriz",
    "Francisco",
    "Carolina",
    "Afonso",
    "Mariana",
    "Tomas",
    "Ana",
    "Miguel",
    "Ines",
    "Guilherme",
    "Margarida",
    "Gabriel",
    "Sofia",
    "Artyom",
    "Sofia",
    "Aleksandr",
    "Anastasia",
    "Roman",
    "Victoria",
    "Yevgeny",
    "Ksenia",
    "Ivan",
    "Arina",
    "Maksim",
    "Yelizaveta",
    "Denis",
    "Adelina",
    "Alexey",
    "Irina",
    "Dmitry",
    "Yelena",
    "Danyl",
    "Polina",
    "Jack",
    "Isla",
    "James",
    "Emily",
    "Oliver",
    "Ava",
    "Rory",
    "Ella",
    "Finlay",
    "Amelia",
    "Lucas",
    "Sophia",
    "Alfie",
    "Evie",
    "Lewis",
    "Maisie",
    "Brodie",
    "Mia",
    "Mason",
    "Aria",
    "Liam",
    "Olivia",
    "Lucas",
    "Emma",
    "Oliver",
    "Amelia",
    "Benjamin",
    "Charlotte",
    "Logan",
    "Chloe",
    "Ethan",
    "Sophia",
    "Noah",
    "Ava",
    "William",
    "Isla",
    "James",
    "Emily",
    "Leo",
    "Abigail",
    "Lucas",
    "Maria",
    "Louis",
    "Marie",
    "Noah",
    "Dominique",
    "Nathan",
    "Martine",
    "Adam",
    "Nathalie",
    "Arthur",
    "Anne",
    "Mohamed",
    "Rita",
    "Kobe",
    "Nicole",
    "Victor",
    "Anna",
    "Mathis",
    "Christiane",
    "An",
    "Ai",
    "Bo",
    "Bi",
    "Cheng",
    "Cai",
    "De",
    "Dan",
    "Dong",
    "Fang",
    "Feng",
    "Hong",
    "Gang",
    "Hui",
    "Guo",
    "Juan",
    "Hui",
    "Lan",
    "Jian",
    "Li",
    "Jakub",
    "Eliska",
    "Jan",
    "Tereza",
    "Tomas",
    "Anna",
    "David",
    "Adela",
    "Adam",
    "Natalie",
    "Matyas",
    "Sofie",
    "Filip",
    "Kristyna",
    "Vojtech",
    "Karolina",
    "Ondrej",
    "Viktorie",
    "Lukas",
    "Barbora",
    "Emil",
    "Aino",
    "Liam",
    "Aada",
    "William",
    "Sofia",
    "Oliver",
    "Eevi",
    "Edvin",
    "Olivia",
    "Max",
    "Lilja",
    "Hugo",
    "Helmi",
    "Benjamin",
    "Ellen",
    "Elias",
    "Emilia",
    "Leo",
    "Ella",
    "Noah",
    "Emma",
    "Leon",
    "Emilia",
    "Matteo",
    "Ella",
    "Paul",
    "Mia",
    "Felix",
    "Marie",
    "Theo",
    "Lina",
    "Elias",
    "Lea",
    "Ben",
    "Mila",
    "Emil",
    "Sophia",
    "Finn",
    "Hannah",
    "Aron",
    "Margret",
    "Alexander",
    "Anna",
    "Viktor",
    "Victor",
    "Emma",
    "Kristjan",
    "Christian",
    "Isabella",
    "Jon",
    "Eva",
    "Guomundur",
    "Kristofer",
    "Hekla",
    "Kristin",
    "Viktoria",
    "Gunnar",
    "Olav",
    "Emilia",
    "Katrin",
    "Jack",
    "Grace",
    "James",
    "Fiadh",
    "Noah",
    "Emily",
    "Daniel",
    "Sophie",
    "Conor",
    "Ava",
    "Finn",
    "Amelia",
    "Liam",
    "Ella",
    "Fionn",
    "Hannah",
    "Harry",
    "Lucy",
    "Charlie",
    "Mia",
    "Leonardo",
    "Sofia",
    "Francesco",
    "Giulia",
    "Alessandro",
    "Aurora",
    "Lorenzo",
    "Alice",
    "Mattia",
    "Ginevra",
    "Andrea",
    "Emma",
    "Gabriele",
    "Giorgia",
    "Riccardo",
    "Greta",
    "Tommaso",
    "Beatrice",
    "Edoardo",
    "Anna",
    "Gabriel",
    "Emma",
    "Leo",
    "Lara",
    "Luca",
    "Zoe",
    "Noah",
    "Amy",
    "David",
    "Sarah",
    "Tom",
    "Charlotte",
    "Ben",
    "Emily",
    "Daan",
    "Anna",
    "Emma",
    "Tess",
    "Noah",
    "Sophie",
    "Sem",
    "Julie",
    "Lucas",
    "Zoe",
    "Jesse",
    "Evi",
    "Finn",
    "Mila",
    "Milan",
    "Sara",
    "Max",
    "Eva",
    "Levi",
    "Fenna",
    "Luuk",
    "Lotte",
    "Jakob",
    "Nora",
    "Emil",
    "Emma",
    "Noah",
    "Ella",
    "Oliver",
    "Maia",
    "Philip",
    "Olivia",
    "William",
    "Emilie",
    "Lucas",
    "Sofie",
    "Liam",
    "Leah",
    "Henrik",
    "Sofia",
    "Oskar",
    "Ingrid",
    "Antoni",
    "Zuzanna",
    "Jakub",
    "Julia",
    "Jan",
    "Lena",
    "Szymon",
    "Maja",
    "Aleksander",
    "Hannah",
    "Franciszek",
    "Zofia",
    "Filip",
    "Amelia",
    "Mikolaj",
    "Alicja",
    "Wojciech",
    "Aleksandra",
    "Kacper",
    "Natalia",
    "Andrei",
    "Maria",
    "David",
    "Ioana",
    "Alexandru",
    "Elena",
    "Stefan",
    "Sofia",
    "Gabriel",
    "Andreea",
    "Cristian",
    "Alexandra",
    "Stefan",
    "Antonia",
    "Luca",
    "Daria",
    "Ionut",
    "Ana",
    "Darius",
    "Gabriel",
    "Mohammad",
    "Sara",
    "Fahd",
    "Latifa",
    "Abdullah",
    "Nora",
    "Abdulrahman",
    "Hessa",
    "Turki",
    "Maysoun",
    "Bandar",
    "Maha",
    "Omar",
    "Nouf",
    "Ali",
    "Noor",
    "Reema",
    "Alanoud",
    "Enzokuhle",
    "Enzokuhle",
    "Lethabo",
    "Melokuhle",
    "Melokuhle",
    "Amahle",
    "Lubanzi",
    "Okuhle",
    "Junior",
    "Lethabo",
    "Siyabonga",
    "Omphile",
    "Bokamoso",
    "Lesedi",
    "Omphile",
    "Rethabile",
    "Amogelang",
    "Amogelang",
    "Thato",
    "Onthatile",
    "Lucas",
    "Alice",
    "Liam",
    "Olivia",
    "William",
    "Astrid",
    "Elias",
    "Maja",
    "Noah",
    "Vera",
    "Hugo",
    "Ebba",
    "Oliver",
    "Ella",
    "Oscar",
    "Wilma",
    "Adam",
    "Alma",
    "Matteo",
    "Lilly",
    "Yusuf",
    "Zeynep",
    "Mirac",
    "Elif",
    "Eymen",
    "Defne",
    "Omer Asaf",
    "Asel",
    "Omer",
    "Azra",
    "Mustafa",
    "Eylul",
    "Kerem",
    "Nehir",
    "Alparslan",
    "Eslem",
    "Hamza",
    "Asya",
    "Ali Asaf",
    "Ecrin",
  ],
  general: [
    "scorp",
    "scrop",
    "guy",
    "fella",
    "cutie",
    "boy",
    "girl",
    "jerk",
    "sting",
  ],
  smokers: [
    "smoke",
    "smokey",
    "smoker",
    "ash",
    "burn",
    "hot",
    "cloud",
    "cough",
    "marlboro",
    "camel",
    "parliament",
    "menthol",
    "clove",
    "spliff",
    "filter",
    "roll",
    "puff",
    "hit",
    "pyro",
    "burno",
  ],
  halo: [
    "divine",
    "revered",
    "worshipper",
    "holy",
    "pious",
    "god",
    "religious",
    "crown",
    "ring",
    "halo",
    "sacred",
  ],
  ballers: [
    "baller",
    "ball",
    "balsy",
    "boxer",
    "tripod",
    "bag",
    "round",
    "circle",
    "maraca",
    "maracas",
    "cue",
    "shark",
    "basketball",
    "football",
    "soccer",
    "tennis",
    "catcher",
    "thrower",
    "squash",
    "racket",
    "federer",
    "nadal",
    "djokovic",
  ],
  druglords: [
    "dealer",
    "plug",
    "drug",
    "druggie",
    "stoner",
    "needle",
    "addict",
    "addiction",
    "user",
    "pill",
    "serum",
    "hormone",
    "high",
    "crazy",
    "bender",
    "intoxicated",
    "detox",
    "toxic",
    "euphoric",
    "whippet",
    "acid",
    "al capone",
    "scarface",
    "coke",
    "cokehead",
    "weed",
    "cannabis",
    "psychonaut",
    "molly",
    "benzo",
  ],
  monos: [
    "color",
    "palette",
    "monochrome",
    "el monocromo",
    "paint",
    "painter",
    "pigment",
    "pig",
    "art",
    "artist",
    "focused",
    "solo",
    "mono",
    "boring",
    "simple",
    "stylish",
    "plain",
    "muted",
    "embossed",
    "boss",
    "stamp",
    "49er",
  ],
  striped: ["stripe", "stripey", "zebra", "bee", "rib", "tiger"],
  claws_unique: [
    "unbalanced",
    "lefty",
    "righty",
    "left",
    "right",
    "ambi",
    "handy",
    "hands",
    "handsy",
    "ambidextrous",
  ],
  claw_big: [
    "big",
    "huge",
    "massive",
    "gigantic",
    "macro",
    "giga",
    "mega",
    "tera",
    "tiny",
    "mini",
    "strong",
    "heavy",
    "tank",
    "body",
    "power",
    "wow",
    "chad",
  ],
  claw_missing: [
    "lacking",
    "gone",
    "invisible",
    "imaginary",
    "fake",
    "faux",
    "missing",
  ],
  boxers: [
    "ali",
    "mayweather",
    "tyson",
    "rocky",
    "socker",
    "smacker",
    "ball",
    "boxer",
    "puncher",
    "punching bag",
    "bowler",
    "pin",
    "bowl",
    "alley",
    "lawrence",
    "okolie",
  ],
  mushies: [
    "shroom",
    "shiitake",
    "mushroom",
    "fungi",
    "fungus",
    "mycologist",
    "growth",
    "truffle",
    "poison",
    "toxic",
    "chanterelle",
    "enoki",
    "morel",
    "puffball",
    "cloud",
    "oyster",
    "magic",
    "lobster",
    "baby bell",
    "fairy",
    "champignon",
    "musho",
  ],
  edwards: [
    "hair",
    "stylist",
    "curly",
    "strait",
    "wavy",
    "kinky",
    "dice",
    "dicer",
    "dicey",
    "chop",
    "chopper",
    "choppy",
    "slice",
    "slicer",
    "slicy",
    "cutter",
    "cut",
    "scissor",
    "scissors",
    "edward",
    "scissorhands",
    "chip chop",
    "snip snip",
  ],
  evil_eyes: [
    "crossed",
    "eyes",
    "evil",
    "monster",
    "anger",
    "stern",
    "scared",
    "angry",
    "scary",
    "face",
    "stare",
    "medusa",
    "gargoyle",
    "mirror",
    "doom",
    "glare",
  ],
  bloody_tails: [
    "bloody",
    "blood",
    "bleeding",
    "wounded",
    "wound",
    "injured",
    "injury",
    "fire",
    "dragon",
    "burning",
    "torch",
  ],
  white_outlines: [
    "ghost",
    "casper",
    "white",
    "snowy",
    "transparent",
    "phantom",
    "ghoul",
    "ghastly",
    "haunt",
    "boo",
    "haunt",
  ],
  blind: [
    "blind",
    "vision",
    "eye",
    "seeing",
    "seer",
    "nearsighted",
    "braille",
    "glasses",
    "monk",
    "window",
    "cane",
  ],
  syringe_tails: [
    "pokey",
    "poke",
    "syringe",
    "sharp",
    "needle",
    "jab",
    "prick",
    "drug",
    "heroin",
    "aids",
    "virus",
    "covid",
    "vaccine",
    "antivaxxer",
  ],
  fat_tails: ["dino", "fatty", "biggie", "big butt", "dinosaur", "beaver"],
  ball_tails: [
    "ball and chain",
    "ball butt",
    "chomp chomp",
    "ampharos",
    "mace",
    "bludgeon",
    "blunt",
    "gada",
    "flail",
    "spice",
  ],
  missing_tails: [
    "tail",
    "no butt",
    "gone",
    "stump",
    "stumpy",
    "tailbone",
    "missing",
  ],
  stubby_legs: ["short", "stub", "stubby", "slow", "stump", "amputee", "dwarf"],
  insect_legs: [
    "insect",
    "buzz",
    "fly",
    "mosquito",
    "bzz",
    "bee",
    "cricket",
    "roach",
    "bug",
    "bugged",
    "art",
    "ant",
    "louse",
    "lice",
    "maggot",
    "infestation",
  ],
  skinny_legs: ["svelte", "skinny", "petite", "lil'", "tiptoe"],
  fat_legs: [
    "fatty",
    "never skips leg day",
    "leg day",
    "squatter",
    "slowpoke",
    "hard to knock over",
    "stomp",
    "stompy",
  ],
};

const MAIN_NAMES = NAME_LIST.top100us
  .concat(NAME_LIST.germanNames)
  .concat(NAME_LIST.globalNames)
  .concat(NAME_LIST.general);

const MANUAL_TAGGED_COLORS = [
  "red",
  "orange",
  "yellow",
  "green",
  "blue",
  "purple",
  "pink",
  "brown(ish)",
  "other",
];

const MANUALLY_TAGGED_SCORP_COLORS = {
  "#2F0043": ["purple"],
  "#2F00FF": ["blue"],
  "#0000FF": ["blue"],
  "#6D0000": ["red"],
  "#6D0043": ["red"],
  "#6D00FF": ["purple"],
  "#B40043": ["red", "pink"],
  "#000043": ["blue"],
  "#002F00": ["green"],
  "#6D009B": ["purple"],
  "#2F009B": ["blue"],
  "#FF2F00": ["red", "orange"],
  "#2F0000": ["red"],
  "#006D00": ["green"],
  "#00009B": ["blue"],
  "#002F43": ["blue"],
  "#006D9B": ["blue"],
  "#2F2F00": ["brown(ish)"],
  "#FF009B": ["pink"],
  "#002FFF": ["blue"],
  "#FF0043": ["red"],
  "#2FFF00": ["green"],
  "#002F9B": ["blue"],
  "#6D2F00": ["brown(ish)"],
  "#00B443": ["green"],
  "#B40000": ["red"],
  "#FF6D00": ["orange"],
  "#2F6D00": ["green"],
  "#2FB400": ["green"],
  "#FF0000": ["red"],
  "#006D43": ["green"],
  "#6D6D00": ["brown(ish)"],
  "#FFFF00": ["yellow"],
  "#00B400": ["green"],
  "#B42F00": ["red", "orange", "brown(ish)"],
  "#00FF43": ["green"],
  "#00B4FF": ["blue"],
  "#00FFFF": ["blue"],
  "#B4FF00": ["green"],
  "#006DFF": ["blue"],
  "#6DFF00": ["green"],
  "#FF00FF": ["pink"],
  "#B4009B": ["pink"],
  "#00B49B": ["green"],
  "#00FF00": ["green"],
  "#FFB400": ["orange"],
  "#6DB400": ["green"],
  "#B4B400": ["yellow"],
  "#B400FF": ["purple"],
  "#00FF9B": ["green"],
  "#B46D00": ["brown(ish)", "orange"],
  "#2F2FFF": ["blue"],
  "#2F6D43": ["green"],
  "#6D6DFF": ["blue"],
  "#2FFF43": ["green"],
  "#2F2F9B": ["blue"],
  "#6DFFFF": ["blue"],
  "#2F6D9B": ["blue"],
  "#2F2F43": ["other"],
  "#6D2F43": ["red", "brown(ish)"],
  "#B42F43": ["red"],
  "#B46D43": ["brown(ish)"],
  "#B4FF9B": ["green"],
  "#6DFF9B": ["green"],
  "#B42F9B": ["purple", "pink"],
  "#B4FF43": ["green"],
  "#B42FFF": ["purple"],
  "#6D6D43": ["other", "brown(ish)"],
  "#B4B49B": ["other", "brown(ish)"],
  "#FF2F43": ["red"],
  "#FF2F9B": ["red", "pink"],
  "#B46DFF": ["purple"],
  "#B46D9B": ["pink", "purple"],
  "#6DB443": ["green"],
  "#6DB49B": ["green"],
  "#FFB49B": ["pink"],
  "#FF6D43": ["orange"],
  "#2FFF9B": ["green"],
  "#6D2FFF": ["blue"],
  "#6D6D9B": ["blue"],
  "#FF6D9B": ["pink"],
  "#FF2FFF": ["pink"],
  "#FFB4FF": ["pink"],
  "#6DB4FF": ["blue"],
  "#B4B4FF": ["purple"],
  "#2FB49B": ["green"],
  "#2FB4FF": ["blue"],
  "#6DFF43": ["green"],
  "#2FB443": ["green"],
  "#FF6DFF": ["pink"],
  "#B4FFFF": ["blue"],
  "#2F6DFF": ["blue"],
  "#FFB443": ["orange"],
  "#FFFF43": ["yellow"],
  "#B4B443": ["yellow"],
  "#FFFF9B": ["yellow"],
  "#2FFFFF": ["blue"],
  "#6D2F9B": ["purple"],
  "#FFFFFF": ["other"],
  "#000000": ["other"],
};

export {
  SCORP_COLORS,
  SORTED_COLOR_DISTRIBUTION,
  NAME_LIST,
  MAIN_NAMES,
  MANUAL_TAGGED_COLORS,
  MANUALLY_TAGGED_SCORP_COLORS,
};
